### ISSUE TITLE
Problem locating commits in correct tag section of changelog

### ISSUE THREAD

**Issue by saix93** [conventional-changelog/conventional-changelog#157] opened 2016-11-28 15:03 UTC
Hello.

I'm having trouble with a certain commit when I try to generate a full changelog.

I have two files, one of them is a full changelog of all versions since v1.0.0.
The other file contains only the changelog of the last version.

The problem is that in the full changelog a certain commit appears in the version  v1.1.0 but should be located in the version v1.2.0 (the last-version changelog logs it correctly)

Example of the full changelog:

`<a name="1.2.0"></a>
# [1.2.0](someUrl/compare/v1.1.0...v1.2.0) (2016-11-25)

<a name="1.1.0"></a>
# [1.1.0](someUrl/compare/v1.0.3...v1.1.0) (2016-11-25)

### Features

* **someFeat:** this is my problematic commit
* **someOtherFeat:** this is another commit`

Example of the last-version changelog that works correctly (v1.2.0):

`<a name="1.2.0"></a>
# [1.2.0](someUrl/compare/v1.1.0...v1.2.0) (2016-11-25)

### Features

* **someFeat:** this is my problematic commit`

Example of the v1.1.0 changelog:

`<a name="1.1.0"></a>
# [1.1.0](someUrl/compare/v1.0.3...v1.1.0) (2016-11-25)

### Features

* **someOtherFeat:** this is another commit`

Here is an image of the commit and branches:

![captura](https://cloud.githubusercontent.com/assets/7765550/20672902/2dfaee0e-b583-11e6-9f92-e83cf9b90b46.PNG)

I don't know if this behaviour is the expected or not, but it seems weird that it performs different in both cases.

If you need anything else, please let me know.

Thank you in advance.

Raúl Torres.

**Comment by stevemao** [comment] 2016-11-29 03:38
Do you have a sample repository to reproduce the problem? Did you tag them properly?

**Comment by saix93** [comment] 2016-11-29 14:36
No, I don't have any repository prepared to test this, sorry.
Yes, I tagged & pushed the tags (I can't really remember if I pushed the first tag before I did the merge from the other branch. Does it matter?)

**Comment by stevemao** [comment] 2017-01-18 22:29
Yes. See [Recommended workflow](https://github.com/conventional-changelog/conventional-changelog-cli#recommended-workflow)

**Comment by Tapppi** [comment] 2017-03-06 19:11
This is expected behavior, since the v1.1.0 tag points to a dead branch (because it was merged into master)? Can this be closed?

**Closed** 2017-03-06 19:12 UTC
