### ISSUE TITLE
Not so convetional, thanks

### ISSUE THREAD

**Issue by isnifer** [conventional-changelog/conventional-changelog#280] opened 2018-02-13 17:11 UTC
You broke my build
![image](https://user-images.githubusercontent.com/1788245/36163282-f9b3a87e-10f9-11e8-99d0-e4fec28b0723.png)

my package-lock.json:
```js
"conventional-changelog": {
  "version": "1.2.0",
  "resolved": "https://registry.npmjs.org/conventional-changelog/-/conventional-changelog-1.2.0.tgz",
  "integrity": "sha1-dJR+c+SLV862hZw3P0+dT7Xm1N8=",
  "dev": true,
  "requires": {
    "conventional-changelog-angular": "1.6.2",
    "conventional-changelog-atom": "0.2.0",
    "conventional-changelog-codemirror": "0.3.0",
    "conventional-changelog-core": "2.0.1",
    "conventional-changelog-ember": "0.3.2",
    "conventional-changelog-eslint": "1.0.0",
    "conventional-changelog-express": "0.3.0",
    "conventional-changelog-jquery": "0.1.0",
    "conventional-changelog-jscs": "0.1.0",
    "conventional-changelog-jshint": "0.3.0",
    "conventional-changelog-preset-loader": "1.1.2"
  }
},
```

And 1.2.0 is not found

**Comment by DenisCarriere** [comment] 2018-02-13 17:12
👍 Same here.. lol oh 🤦‍♂️

**Comment by ardeois** [comment] 2018-02-13 17:15
Looks like a duplicate of https://github.com/conventional-changelog/conventional-changelog/issues/279

**Comment by DenisCarriere** [comment] 2018-02-13 17:19
Agreed, we should close this issue

**Closed** 2018-02-13 17:19 UTC
