### ISSUE TITLE
conventional-changelog with bitbucket

### ISSUE THREAD

**Issue by Youcongcong** [conventional-changelog/conventional-changelog#336] opened 2018-06-06 07:43 UTC
The link address for the generated log is incorrect, for example
merge develop ([eae76d9](http://git.ascs.tech/website/cityworks_hubpage/commits/eae76d9)) 
The link above is wrong, and the correct one should be ‘https://bitbucket.ascs.tech/projects/WEBSITE/repos/upm/commits/f294f3cb52924db998c8cbfc4798b826f6a9b912’

**Comment by hbetts** [comment] 2018-06-06 13:33
@Youcongcong how can we reproduce the error you're seeing?

**Comment by Youcongcong** [comment] 2018-06-07 06:02
I use the command : conventional-changelog -p angular -i CHANGELOG.md -s
And then I'm going to generate changlog . But the submit history link generated inside is wrong.

**Comment by evolutionxbox** [comment] 2018-11-16 23:21
Having a similar issue.

Links should be in the format `https://<url>/projects/<PROJECT>/repos/<repo>/commits/<sha>`, but the output is currently `http://<url>/<project>/<repo>/commits/<sha>`.

A way to specify custom URLs would be handy.

**Comment by NateScarlet** [comment] 2019-03-26 07:18
Similar issue with gitea

**Comment by stevemao** [comment] 2019-03-26 23:32
duplicate of https://github.com/conventional-changelog/conventional-changelog/issues/185#issuecomment-299751252

**Closed by stevemao** 2019-03-26 23:32 UTC
