### ISSUE TITLE
Add support for bitbucket

### ISSUE THREAD

**Issue by codeNoobie** [conventional-changelog/conventional-changelog#353] opened 2018-07-12 03:38 UTC
Is anyone using conventional-changelog with bitbucket? The links generated in change log is broken for bitbucket. How are people using this?
I can see below third party lib. Is this supported natively by conventional-changelog?
https://github.com/uglow/conventional-changelog-angular-bitbucket

**Comment by jhabdas** [comment] 2018-07-31 06:10
@codeNoobie I believe what you're looking for is a [releaser-tool](https://github.com/conventional-changelog/releaser-tools) for bitbucket. Given this entire suite of tools is written in a modular fashion you may have better luck looking through the forks.

**Comment by hbetts** [comment] 2018-08-05 22:13
Individual commit lines in a project's changelog are rendered by `conventional-changelog-writer` using [this template](https://github.com/conventional-changelog/conventional-changelog/blob/0e05028f70bbd3109e1a4b16262a9450153060de/packages/conventional-changelog-writer/templates/commit.hbs).

@codeNoobie can you please share an example of a changelog with broken links? (This may be related to #336)

**Comment by stevemao** [comment] 2019-01-25 04:59
If anyone want to submit a PR, please read https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/21#issuecomment-263088224

**Comment by stevemao** [comment] 2019-03-26 23:33
duplicate of https://github.com/conventional-changelog/conventional-changelog/issues/185#issuecomment-299751252

**Closed by stevemao** 2019-03-26 23:33 UTC
Labels: enhancement, help wanted
